### ISSUE TITLE
MiniAVC doesn't do anything without a version file

### ISSUE THREAD

**Issue by HebaruSan** [RJVB09/Dreskiller-Base#1]
## Problems

While reviewing KSP-CKAN/NetKAN#8319, I noticed that this mod bundles MiniAVC.dll and MiniAVC.xml, however there is no version file in the ZIP for MiniAVC to use. I believe this means it will just take up a few CPU cycles looking for the file and then exit without actually doing anything.

## Suggestions

- Remove MiniAVC.dll and MiniAVC.xml
OR:
- Add a version file

Most of the time a planet pack doesn't need a version file because it doesn't depend on specific game versions, so the first option is probably adequate.

**Comment by RJVB09** [comment]
MiniAVC.ddl and .xml got deleted.
